name: 'Auto Assign Reviewer and Assignee'

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  add-reviewers-and-assignee:             
    runs-on: ubuntu-latest              
    steps:
      - uses: hkusu/review-assign-action@v1
        with:
          github-token: ${{ secrets.ACTION_TOKEN }}
          assignees: ${{ github.actor }}
          reviewers: jinho-yoo-jack
