name: on-premise-cicd
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Set Tags Name'
        required: true
        default: master

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      release: ${{ steps.set-version.outputs.VERSION_NAME }}
    steps:
      - id: set-version # v1.0.0 -> v1-0-0
        run: |
          echo "VERSION_NAME=$(echo "${{ github.event.inputs.tags }}" | sed "s/\./\-/g")" >> $GITHUB_OUTPUT

      - name: Check Version Name
        run: |
          echo "Check Version -> ${{ steps.set-version.outputs.VERSOIN_NAME }}"

      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          ref: '${{ github.event.inputs.tags }}'

      - name: Grant execute permission for gradlew
        run: chmod +w gradlew

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Build with Gradlew
        run: ./gradlew clean test bootJar

      - name: Add version
        run: |
          mv build/libs/cicd-study-0.0.1-SNAPSHOT.jar build/libs/cicd-study-${{ steps.set-version.outputs.VERSION_NAME }}.jar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cicd-study-application # cicd-study-application.zip
          path: build/libs/cicd-study-${{ steps.set-version.outputs.VERSION_NAME }}.jar